---
- name: Backup original CentOS repo files
  command: mv /etc/yum.repos.d/CentOS-Linux-*.repo /etc/yum.repos.d/backup/
  args:
    removes: /etc/yum.repos.d/backup/
  ignore_errors: yes

- name: Configure CentOS Vault repositories
  copy:
    dest: /etc/yum.repos.d/CentOS-Vault.repo
    content: |
      [baseos]
      name=CentOS-$releasever - Base
      baseurl=http://vault.centos.org/8.5.2111/BaseOS/$basearch/os/
      gpgcheck=1
      enabled=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial

      [appstream]
      name=CentOS-$releasever - AppStream
      baseurl=http://vault.centos.org/8.5.2111/AppStream/$basearch/os/
      gpgcheck=1
      enabled=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial

      [extras]
      name=CentOS-$releasever - Extras
      baseurl=http://vault.centos.org/8.5.2111/extras/$basearch/os/
      gpgcheck=1
      enabled=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial

