---
- name: Install Apache
  dnf:
    name: httpd
    state: present

- name: Ensure Apache service enabled
  service:
    name: httpd
    state: started
    enabled: yes

- name: Deploy dynamic index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0444'
  notify: Restart Apache

